security:
    enable_authenticator_manager: true

    hide_user_not_found: false

    role_hierarchy:
        ROLE_USER: ['ROLE_FREELANCER', 'ROLE_CLIENT']
    
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        #    algorithm: plaintext

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            entry_point: form_login
            custom_authenticator: App\Security\LoginFormAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                enable_csrf: true

            logout: true

            login_throttling: 
                max_attempts: 3

            remember_me:
                secret: '%kernel.secret%'
                always_remember_me: true
                signature_properties: [password]
  
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }   