# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
                    $stripeSK: "%env(STRIPE_SK)%"

            # $formLoginAuthenticator: '@security.authenticator.form_login.main'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
           
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
# config/services.yaml
parameters:
    pdf_directory: '%kernel.project_dir%/public/pdf'
    imageCategorie: '%kernel.project_dir%/public/uploads/categories'
    imageOffre: '%kernel.project_dir%/public/uploads/imageOffre'

# # config/packages/mercuryseries_flashy.yaml
# mercuryseries_flashy:
#     # The name to use as the flash message key in the session store
#     flash_message_name:   mercuryseries_flashy_notification

    # The session store to use for storing flash messages
    session_store: null
    App\Service\TwilioClient:
        arguments:
            $accountSid: 'AC996f5d67ff7718f75549161540ba1e32'
            $authToken: '57ae0c797a8253df22be61086378c3ba'
